server:
  port: 9013

spring:
  # RabbitMQ配置
  rabbitmq:
    host: 192.168.10.141
    port: 5672
    username: admin
    password: ibdw@123
    # 虚拟主机（默认为/）
    virtual-host: /

    # 消息确认配置
    publisher-confirm-type: correlated  # 发布确认模式
    publisher-returns: true             # 消息返回
    template:
      mandatory: true                   # 消息无法路由时返回给发送者

    # 消费者配置
    listener:
      simple:
        acknowledge-mode: manual        # 手动确认模式
        prefetch: 1                     # 预取数量，实现公平分发
        concurrency: 3                  # 消费者并发数量
        max-concurrency: 10             # 最大消费者并发数量
        default-requeue-rejected: false # 拒绝的消息不重新入队（进入死信队列）

        # 重试配置
        retry:
          enabled: true                 # 启用重试机制
          max-attempts: 3               # 最大重试次数
          initial-interval: 2000        # 初始重试间隔（毫秒）
          multiplier: 2.0               # 重试间隔倍数
          max-interval: 10000           # 最大重试间隔（毫秒）
          stateless: true               # 无状态重试
    config:
      delayed-queue: delayed.queue
      delayed-dlq: delayed.queue.dlq
      normal-queue: normal.queue
      normal-dlq: normal.queue.dlq
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
    password:
  jackson:
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.141:33068/nblg_apply?allowPublicKeyRetrieval=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: ibdw@1608
    maxActive: 4
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    asyncInit: true
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true


logging:
  level:
    org.example.controller: info
  config: classpath:logback-spring.xml
  path: ./logs

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true

wechat:
  miniapp:
    appid: wxc95d7055b5724a1c
    secret: f9d537cbaf55b13a9819ee63072cdbd4